insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (1, 'Alton' , 'Omega Business Park' ,'' ,'Alton' ,' GU34 2QE')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (2, 'Bordon' , 'Station Road' ,'' ,'Bordon' ,' GU35 0LG')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (3, 'Netley' , 'Grange Road' ,'' ,'Southampton' ,' SO31 5FF')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (4, 'Efford' , 'Milford Road Pennington' ,'' ,'Lymington' ,' SO41 8EZ')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (5, 'Havant' , 'Harts Farm Way' ,'' ,'Havant' ,' PO9 1HS')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (6, 'Andover' , 'Scott Close Walworth Industrial Estate' ,'' ,'Andover' ,' SP10 5NU')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (7, 'Gosport' , 'Grange Road' ,'' ,'Gosport' ,' PO13 8AS')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (8, 'Somerley' , 'Verwood Road' ,'' ,'Ringwood Forest' ,' BH24 3QE')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (9, 'Casbrook' , 'Casbrook Bunny Lane' ,'Timsbury' ,'Romsey' ,' SO51 0PG')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (10, 'Southampton' , 'City Depot' ,'Dock Gate 20' ,'outhampton' ,' SO15 0LJ')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (11, 'Marchwood' , 'Normandy Way' ,'Marchwood' ,'Southampton' ,' SO40 4UD')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (12, 'Eastleigh' , 'Stoney Croft Rise Chandlers Ford' ,'' ,'Eastleigh' ,' SO53 3YU')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (13, 'Aldershot' , 'Ivy Road' ,'North Lane' ,'Aldershot' ,' GU12 4TX')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (14, 'Portsmouth' , 'Paulsgrove Portway' ,'' ,'Port Solent' ,' PO6 4UD')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (15, 'Winchester' , 'Bar End Industrial Estate' ,'Bar End Road' ,'Winchester' ,' SO23 9NP')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (16, 'Farnborough' , 'Eelmoor Road' ,'' ,'Farnborough' ,' GU14 7QN')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (17, 'Basingstoke' , 'Wade Road' ,'' ,'Basingstoke' ,' RG24 8PL')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (18, 'Segensworth' , 'Barnes Wallis Road' ,'Segensworth' ,'Fareham' ,' PO15 5TS')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (19, 'Petersfield' , 'Bedford Road' ,'' ,'Petersfield' ,' GU32 3LJ')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (20, 'Fair Oak' , 'Knowle Lane' ,'Fair Oak' ,'Eastleigh' ,' SO50 7DZ')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (21, 'Hedge End' , 'Shamblehurst Lane' ,'Hedge End' ,'Southampton' ,' SO30 2AD')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (22, 'Waterlooville' , 'Darnell Road' ,'' ,'Waterlooville' ,' PO7 7TX')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (23, 'New Alresford' , 'Prospect Road' ,'' ,'New Alresford' ,' SO24 9QF')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (24, 'Hayling Island' , 'Fishery Lane' ,'' ,'Hayling Island' ,' PO11 9NR')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (25, 'Bishops Waltham' , 'Claylands Road' ,'Bishops Waltham' ,'Southampton' ,' SO32 1BH')
insert into CollectionCentreDim (CentreID, CentreName,  FirstLine, SecondLine, City, PostCode) values (26, 'Hartley Wintney' , 'Springwell Lane' ,'Hartley Wintney' ,'Hook' ,' RG27 8BW')
