insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Aluminium' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Baths' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Batteries' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Bedding and quilts and pillows and sleeping bags' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Car batteries' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Cardboard' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Carpets' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Christmas trees - real' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Clothing' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Electrical equipment and appliances' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Foil' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Fridges/freezers' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Garden waste' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Lawnmowers' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Light bulbs' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Mattress' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Mobile phones' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Printer cartridges' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Scrap metal' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Textiles' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted' , 'Tins Wallpaper' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Animal waste' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Asbestos' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Engine oil' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Fire extinguishers' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Furniture' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Gas bottles' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Household and garden chemicals' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Paint' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Pesticides' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Plasterboard' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Rubble' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Sinks and toilets' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Soil' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Upholstered domestic seating' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Accepted with restrictions' , 'Wood' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Ammunition' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Cartons' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Clinical waste and sharps/healthcare' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Cooking oil' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Explosives' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Flares' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Fuel - petrol or diesel' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Glass bottles and jars' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Medicines' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Tyres' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Yellow pages' )
insert into WasteTypeDim (WasteTypeID, Restriction, Name) values (1, 'Not accepted' , 'Yoghurt pots' )
