insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (1, 'Accepted' , 'Aluminium' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (2, 'Accepted' , 'Baths' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (3, 'Accepted' , 'Batteries' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (4, 'Accepted' , 'Bedding and quilts and pillows and sleeping bags' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (5, 'Accepted' , 'Car batteries' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (6, 'Accepted' , 'Cardboard' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (7, 'Accepted' , 'Carpets' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (8, 'Accepted' , 'Christmas trees - real' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (9, 'Accepted' , 'Clothing' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (10, 'Accepted' , 'Electrical equipment and appliances' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (11, 'Accepted' , 'Foil' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (12, 'Accepted' , 'Fridges/freezers' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (13, 'Accepted' , 'Garden waste' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (14, 'Accepted' , 'Lawnmowers' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (15, 'Accepted' , 'Light bulbs' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (16, 'Accepted' , 'Mattress' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (17, 'Accepted' , 'Mobile phones' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (18, 'Accepted' , 'Printer cartridges' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (19, 'Accepted' , 'Scrap metal' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (20, 'Accepted' , 'Textiles' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (21, 'Accepted' , 'Tins Wallpaper' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (22, 'Accepted with restrictions' , 'Animal waste' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (23, 'Accepted with restrictions' , 'Asbestos' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (24, 'Accepted with restrictions' , 'Engine oil' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (25, 'Accepted with restrictions' , 'Fire extinguishers' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (26, 'Accepted with restrictions' , 'Furniture' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (27, 'Accepted with restrictions' , 'Gas bottles' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (28, 'Accepted with restrictions' , 'Household and garden chemicals' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (29, 'Accepted with restrictions' , 'Paint' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (30, 'Accepted with restrictions' , 'Pesticides' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (31, 'Accepted with restrictions' , 'Plasterboard' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (32, 'Accepted with restrictions' , 'Rubble' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (33, 'Accepted with restrictions' , 'Sinks and toilets' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (34, 'Accepted with restrictions' , 'Soil' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (35, 'Accepted with restrictions' , 'Upholstered domestic seating' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (36, 'Accepted with restrictions' , 'Wood' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (37, 'Not accepted' , 'Ammunition' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (38, 'Not accepted' , 'Cartons' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (39, 'Not accepted' , 'Clinical waste and sharps/healthcare' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (40, 'Not accepted' , 'Cooking oil' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (41, 'Not accepted' , 'Explosives' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (42, 'Not accepted' , 'Flares' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (43, 'Not accepted' , 'Fuel - petrol or diesel' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (44, 'Not accepted' , 'Glass bottles and jars' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (45, 'Not accepted' , 'Medicines' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (46, 'Not accepted' , 'Tyres' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (47, 'Not accepted' , 'Yellow pages' )
insert into WasteTypeDim (WasteTypeID, Restriction, WasteName) values (48, 'Not accepted' , 'Yoghurt pots' )
